export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_MODE = 'SET_MODE'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_SHOW_MESSAGE = 'SET_SHOW_MESSAGE'

export const SET_MESSAGE_TEXT = 'SET_MESSAGE_TEXT'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'
